### PR TITLE
add storage_specification to schema and add link to rdf file_format

### PR DESCRIPTION
**Pull request by ferrighi**
Adding link to rdf data format in documentation and change example according to skos:prefLabel. 
Adding schema validation for all but file_format for now.

### CODE REVIEW

**Comment by steingod** [comment]
Any reason why file_format is commented out in the schema?

**Comment by ferrighi** [comment]
I have been looking at how to validate the xml using the external skos vocabulary prefLabel, but i have not found a good example so far. So I will have to complete that, thus I have left it out for now. If you have an example to follow I can implement it.

**Comment by steingod** [comment]
Shouldn't we keep the element and rather add the content validation later?

**Comment by ferrighi** [comment]
I've uncommented it. We can add the list for content validation later.

**Pull request merged**
