### PR TITLE
CI for building docs, and for tests and coverage reports

### LINKED ISSUE #74: Write unit tests and integrate with CI system, including Coveralls
The repo lacks proper testing routines. We should

- Write unit tests for python code
- Consider how to test the xml, xsd, and xslt files (perhaps using python unit tests as well?)
- Setup Travis CI
- Setup Coveralls
- Get badges on README

It will not be possible to get anything close to 100% test coverage now but at least we should try to set up a good workflow.

### PR DESCRIPTION
**Pull request by mortenwh**
* Changed name of folder `src` to `mmd_utils`
* Added folder `bin` to contain executables
* Moved perl code to own folder
* Initial refactoring of code that was in the `src` folder (to be followed up in #81)
* Added automatic building of docs (html and pdf files) on every push
* Added a few unit tests for the code now in `mmd_utils` - this needs further development
* Added coverage reporting on push

  * coverage is low and needs improvement
  * coverage checks all content, except the test folder - this may be changed but requires some discussion

* Added unit testing on push
* Added badges for builds, tests and coverage
* Cleaned up `nc_to_mmd.py` to make it compatible with the PEP8 convention

This PR can be squashed and merged when approved. That will close #74.

Note:

* steingod/mmd must be linked to Coveralls - I think maybe @steingod needs to create an account there
* The Coveralls badge must be updated and maybe refer to HEAD. Looks like a merge request doesn't tell coveralls it's master. May be different if you push directly to master.
* Badges in README.md must be replaced
* COVERALLS_REPO_TOKEN must be added to the repositories secrets with coveralls token.

### CODE REVIEW

**Comment by mortenwh** [comment]
Note:
* steingod/mmd must be linked to Coveralls - I think maybe @steingod needs to create an account there
* The Coveralls badge must be updated and maybe refer to HEAD. Looks like a merge request doesn't tell coveralls it's master. May be different if you push directly to master.
* Badges in README.md must be replaced
* COVERALLS_REPO_TOKEN must be added to the repositories secrets with coveralls token.

**Comment by ferrighi** [comment]
1) This is kind of big refactoring. It would probably be good to have 2 reviews. 

2) I looked briefly to the nc_to_mmd.py modifications, from my point of view this 
script should take CF/ACDD compliant files and make all possible translation. 
It should not contain specific attributes that apply only to some internal files. 
I would suggest that if you need to create/add something specific you do it separately.

3) Executables are not working unless PYTHONPATH inclues the mmd_utils directory, and this
is not what I would expect from an executable. 

4) With respect to linking this repository outside of git, creating an account for coverage
is taking a path that I think we should discuss a bit more in details, as it is linked to a specific 
person, but if so, it should surely be on the repository owner. I'm concerned when we start adding 
too many of these features we might over complicate it, and maybe fall outside the scope of this
repository.  

5) My suggestion here is to open a work-in-progress branch instead on merging now to master, so that we can push to this branch until we are all happy with the tests, documentation on how to run them and so on.

**Comment by mortenwh** [comment]
>     1. This is kind of big refactoring. It would probably be good to have 2 reviews.

Yes - I'll assign @steingod :)
> 
>     2. I looked briefly to the nc_to_mmd.py modifications, from my point of view this
>        script should take CF/ACDD compliant files and make all possible translation.
>        It should not contain specific attributes that apply only to some internal files.
>        I would suggest that if you need to create/add something specific you do it separately.

I see. This is an update that Trygve needed to create the MMD files. He used my fork for practical reasons linked to the refactoring that was ongoing here. As far as I understand, these changes shouldn't break anything, although this can only be verified by tests which still need to be implemented.

Based on the principle that metadata should follow the data, we concluded that it was best to include everything in the netcdf files... Anyway - perhaps this is something that could be worked on together with @TAlonglong and @hevgyrt after the merge? There is a lot of testing and docstrings that need to be added. Especially if new people are supposed to use it and help to develop it.

>     3. Executables are not working unless PYTHONPATH inclues the mmd_utils directory, and this
>        is not what I would expect from an executable.

The previous src folder was a mixture of executable code and class definitions in the same modules. This is not good practice. The executables should just import and run the relevant tools, i.e., using the `mmd_utils` package, which can also be used from other tools than the command line. As part of further development, we should have a file `setup.py` to make the installations but until then, I presume people are able to handle the installation themselves by adding a link from `site-packages` or add the package to the pythonpath in some other way.

>     4. With respect to linking this repository outside of git, creating an account for coverage
>        is taking a path that I think we should discuss a bit more in details, as it is linked to a specific
>        person, but if so, it should surely be on the repository owner. I'm concerned when we start adding
>        too many of these features we might over complicate it, and maybe fall outside the scope of this
>        repository.

I kind of disagree here. Coverage testing is very important and will help people realize the need for making more tests, and to easily monitor if we're actually testing enough of the code. We could of course try to find and evaluate other technical solutions but coveralls is straightforward and works. Not something that I would recommend spending time on.

>     5. My suggestion here is to open a work-in-progress branch instead on merging now to master, so that we can push to this branch until we are all happy with the tests, documentation on how to run them and so on.

It is quite common to have develop branches. This could be introduced but might not be practical before we move the repo to metno? Also, since we just made a new release (I suppose it is tagged) people can use that version, whereas development continues in the master branch.

**Comment by ferrighi** [comment]
1) good. 
2) Sure, we can review the nc_to_mmd script. I'm pretty sure it does not break anything, as translates only what is found. What I am thinking about is that, for example, you can link license (acdd) with the resource url through a match outside the nc file, so that it can be more generic. Nothing critical.
3) Presuming that people knows is usually a big assumption. I guess a line in the README could do. 
4) I have not big feelings about this. I was just pointing out that we should not loose the purpose of the repository, which for me is to provide mmd specifications and schema, together with xslt files. All other things are good and welcome, as examples and tools, but not central from my perspective. So a test suite is good to have, making translations and checking against schemas, if we need external resource for this, @steingod should be the one creating the account I think.

**Comment by steingod** [comment]
I would like to discuss issue 4 mentioned above a bit more just to make sure we are not creating a potential bottleneck for future updates to the specification.

**Comment by mortenwh** [comment]
Regarding point 4 above - yes, I agree that each repo should only be concerned about its actual purpose. That probably means that Python and Perl code, etc., should be moved somewhere else. However, everything in any case needs to be tested. Here, you have the recipe for that. Next will be to refactor even more, and probably to figure out good ways to test the specification for typos etc.

**Comment by mortenwh** [comment]
What is the status here? Can this be merged?

**Pull request merged**
