### PR TITLE
Added storage information for datasets. This is primarily for local use.

### PR DESCRIPTION
**Pull request by steingod**
Added information enabling handling of storage locations and checksums. There are no such support in information exchanged in ISO19115 or GCMD DIF currently.

### CODE REVIEW

**Comment by steingod** [comment]
The conflict is my fault since I upgraded this after I submitted the PR. I would prefer that by principle one of the reviewers do the merge.

**Comment by mortenwh** [comment]
Ok - I'll let @ferrighi have look before merging

**Comment by ferrighi** [comment]
I am not sure I understand file_location, what is a local file storage? In the example it's just a local path. We should also add a vocabulary for the file formats then. Is it just limited to netCDF/CF as for now?

**Comment by steingod** [comment]
Yes it is the file system location. It could be other formats as well, but I still think we should stick with self explaining formats whenever possible.Possible options not using a self developed could be:
- https://github.com/wmo-im/wmds/blob/master/tables/7-07.csv
- https://gcmdservices.gsfc.nasa.gov/kms/concepts/concept_scheme/GranuleDataFormat/?format=csv

I would prefer the latter for now since it is more comprehensive or a combination (through identification of vocabulary) which will create more work for us.

**Comment by ferrighi** [comment]
Ok, I still fail to see the relevance of this path in this format, if I don't know how to access the storage location, or even if I have access to it. I am trying to understand what I can do with this information...But I am sure you have the picture in mind. 

For the vocabulary. Should I then add a vocabulary with the second list you have sent? it looks a bit too extensive for our use maybe, we could extract some from there and keep it as local vocabulary, as I don't think there is much maintenance to be done in the future. 

Should I add a vocabulary with the checksum as well?

**Comment by steingod** [comment]
I am not sure I understand the issue you raise here. I can understand the comment in a distributed data management perspective, but the purpose of this record is also for internal use and then you would have access. It will bridge towards other systems that are to be integrated, like produktstatus and it will help establishing workflows internally. It is not intended for use on harvested metadata and datasets we do not control ourselves. Is that the issue you are raising or?

I think we should use the second list, which neither is extensive since most formats are or have been in use internally. But do we need to create our own, can't we just use the RDF version available at https://gcmdservices.gsfc.nasa.gov/kms/concepts/concept_scheme/GranuleDataFormat/?

**Comment by ferrighi** [comment]
I got it, yes. I have prepared a PR #59 to add the link to the rdf file and validation in the schema. We miss so far to include the validation of file_format using the skos vocabulary. For now I say that if @steingod merges #59, then @mortenwh can merge and close this PR.

**Comment by steingod** [comment]
@mortenwh will you merge and close this?

**Pull request merged**
