### PR TITLE
Tools update

### PR DESCRIPTION
**Pull request by magnarem**
To be merged with master.

NOTE: 
the convert-to-mmd.py and convert-from-mmd.py are to be run from mmd-repo root dir.
Example: ./src/convert-to-mmd.py instead of running from src-dir like ./convert-to-mmd.py
This is done so the scripts know where to finde the xslt and xsd schemas.
All sctripts in src folder should maybe be modified to work in the same way. either by running them from mmd-root dir or src dir.

### CODE REVIEW

**Comment by ferrighi** [comment]
@magnarem I suggest you remove the script directory and add a BUILDING.md containing: 

```
$ gem install asciidoctor
$ gem install --pre asciidoctor-pdf

$ asciidoctor -B doc/ doc/mmd-specification.adoc
$ asciidoctor-pdf -B doc/ -D doc/ doc/mmd-specification.adoc 

```

**Comment by magnarem** [comment]
scripts directory removed and BUILDING.md doc added

**Comment by ferrighi** [comment]
Good! @hevgyrt or @magnarem could you resolve the conflict and assign the merging to @steingod

**Comment by magnarem** [comment]
comments to conflicting files.

README.me: changed formatting to code for documentantion generation commands.

xslt/dif-to-mmd.xsl: Added string search replace function, for changing enumerating keywords to conform with schema.

**Pull request merged**
